name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: 19.2.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_USERNAME: ${{secrets.USERNAME}}
          CYPRESS_PASSWORD: ${{secrets.PASSWORD}}